import './css/style.css'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@ant-design/v5-patch-for-react-19';
import { SessionProvider } from 'next-auth/react';
import Providers from './providers/providers';


export const metadata = {
  title: "ПОЧТА РОССИИ ПВЗ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}


