import './css/style.css'
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: "ПОЧТА РОССИИ ПВЗ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          {children}
        </AntdRegistry> 
      </body>
    </html>
  );
}


