import React from 'react';
import { Button, Result } from 'antd';

export const metadata = {
    title: "404 - Page Not Found",
    description: "Generated by create next app",
};

const App = () => (
  <Result
    status="404"
    title="404"
    subTitle="Похоже мы потеряли эту страницу"
    extra={<Button type="primary" size="large" variant="solid" color='purple'>На главную</Button>}
  />
);
export default App;