import LayoutMain from "../../../layout/layounMain/layoutMain";

export const metadata = {
  title: "Приём посылок",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LayoutMain>
      {children}
    </LayoutMain>
  );
}
