import { AntdRegistry } from "@ant-design/nextjs-registry";
import { SessionQuery } from "./provider/session";

export const metadata = {
  title: "PochtaAPI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="ru">
      <body style={{ backgroundColor: '#EAEAEA' }}>
        <AntdRegistry>
          <SessionQuery>
            {children}
          </SessionQuery>
        </AntdRegistry>
      </body>
    </html>
  );
}
