import { SessionQuery } from "./provider/session";

export const metadata = {
  title: "PochtaAPI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="ru">
      <body style={{ backgroundColor: '#EAEAEA' }}>
        <SessionQuery>
          {children}
        </SessionQuery>
      </body>
    </html>
  );
}
